steps:
  - name: gcr.io/cloud-builders/docker
    args: ["build", "-t", "gcr.io/$PROJECT_ID/sample-gke:latest", "-t", "gcr.io/$PROJECT_ID/sample-gke:$REVISION_ID", "."]
  - name: gcr.io/cloud-builders/docker
    args: ["build", "-t", "gcr.io/$PROJECT_ID/sample-gke-nginx:latest", "-t", "gcr.io/$PROJECT_ID/sample-gke-nginx:$REVISION_ID", "nginx"]
  - name: gcr.io/cloud-builders/docker
    args: ["push", "gcr.io/$PROJECT_ID/sample-gke"]
  - name: gcr.io/cloud-builders/docker
    args: ["push", "gcr.io/$PROJECT_ID/sample-gke-nginx"]
  - name: gcr.io/sandbox-hara/kubectl
    env:
      - 'PROJECT_ID=$PROJECT_ID'
      - 'REVISION_ID=$REVISION_ID'
