apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: go-sample
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: go
    spec:
      containers:
      - name: go-sample
        image: ryutah/sample-gke
        ports:
          - containerPort: 8080
